<?xml version="1.0" encoding="UTF-8" ?>
<testsuites id="2019_05_08_00_12_31_demo_junitXmlReport" failures="1" name="demo_junitXmlReport" time="0h:0m:7s:584ms" tests="3">
   <testsuite id="1" failures="0" name="SuccessfullTest" time="0h:0m:0s:32ms" tests="1">
      <testcase time="0h:0m:0s:24ms" id="1" name="main.java.projects.mock.testCases.MockSuccess">

      </testcase>
   </testsuite>
   <testsuite id="2" failures="1" name="SeleniumExceptionTest" time="0h:0m:4s:334ms" tests="2">
      <testcase time="0h:0m:0s:483ms" id="1" name="main.java.projects.mock.testCases.MockException">
         <failure message="FAILURE" type="ERROR">
main.java.base.failures.Failure: Test case exception!
         </failure>
      </testcase>
      <testcase time="0h:0m:0s:0ms" id="2" name="main.java.projects.mock.testCases.MockSuccess">

      </testcase>
   </testsuite>
   <testsuite id="3" failures="0" name="SeleniumJsErrorTest" time="0h:0m:3s:203ms" tests="2">
      <testcase time="0h:0m:0s:561ms" id="1" name="main.java.projects.mock.testCases.MockJSError">

      </testcase>
      <testcase time="0h:0m:0s:12ms" id="2" name="main.java.projects.mock.testCases.MockSuccess">

      </testcase>
   </testsuite>
</testsuites>